### ISSUE TITLE
Roadmap for v0.1.0

### ISSUE THREAD

**Issue by Padarom** [hourglass/hourglass#10]
This issue serves as the roadmap for Hourglass. It's an overview of what we're planning to do before releasing v0.1.0. Please keep in mind that the list can change at any point.

## General plans
**v0.1.0** should be considered the first stable version of Hourglass. Keep in mind, that Hourglass consists of the backend portion, which drives the rest of the project, and the forum portion in the shape of an addon. As such, v0.1.0 will focus completely on the core (_Backend_) and a functional addon API and will likely not contain a lot of forum functionality.

- [ ] Create installer for new projects
- [ ] Test coverage for most components
- [ ] Functional user management
- [ ] Functional page configuration
- [ ] Streamlined upgrade process
- [ ] Backend and frontend authentication
- [ ] Addon Support
  - [ ] Install addons via composer, zip file or manually
  - [ ] Database migrations
  - [ ] Asset publishing
  - [ ] Template and Code Events
